parent_config: "configs/waymo/waymo_base.yaml"
source_dir: "/data1/dataset/lidar-rt/waymo_perception_v1.4.3/dynamic/2/"

frame_length: [51, 100]
eval_frames: [60, 70, 80, 90]

scene_id: wd2

dynamic: True
