parent_config: "configs/waymo/waymo_base.yaml"
source_dir: "/data1/dataset/lidar-rt/waymo_perception_v1.4.3/dynamic/3"

frame_length: [1, 50]
eval_frames: [10, 20, 30, 40]

scene_id: wd3

dynamic: True
