parent_config: "configs/waymo/waymo_base.yaml"
source_dir: "/data1/dataset/lidar-rt/waymo_perception_v1.4.3/dynamic/4"

frame_length: [148, 197]
eval_frames: [158, 168, 178, 197]

scene_id: wd4

dynamic: True
