parent_config: "configs/kitti360/kitti_base.yaml"

# frame_length: [2351, 2400]
# eval_frames: [2360, 2370, 2380, 2390]

#! debug
frame_length: [2358, 2366]
eval_frames: [2363]

scene_id: kd1

dynamic: True

